-- ============================================================
-- IB Calendar OS — full schema, migrations 001-012 combined.
--
-- Generated by concatenating supabase/migrations/*.sql in filename order.
-- Run this on a FRESH Supabase project. On a project that already has some
-- migrations applied, run the individual files you are missing instead.
-- ============================================================


-- ─────────── 001_foundation.sql ───────────
-- ============================================================================
-- 001_foundation.sql
-- Identity, preferences, the energy model, calendars and IB subjects.
--
-- Conventions used across every migration in this project:
--   * All instants are timestamptz. Wall-clock preferences (sleep, day start)
--     are `time` and are interpreted in profiles.timezone.
--   * All durations are integer MINUTES. Never floats — the scheduling engine
--     must be bit-for-bit deterministic and float minutes destroy that.
--   * Every user-owned table carries user_id and has RLS forcing auth.uid().
-- ============================================================================

create extension if not exists pgcrypto;
create extension if not exists btree_gist;

-- ---------------------------------------------------------------------------
-- Shared helpers
-- ---------------------------------------------------------------------------

create or replace function set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- profiles
-- ---------------------------------------------------------------------------

create table profiles (
  id           uuid primary key references auth.users (id) on delete cascade,
  display_name text,
  -- IANA zone. Validated in the app via Intl.supportedValuesOf('timeZone');
  -- a CHECK cannot call the tz database from an IMMUTABLE context.
  timezone     text        not null default 'UTC',
  ib_session   text,
  onboarded_at timestamptz,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create trigger profiles_updated_at
  before update on profiles
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- user_settings — the capacity envelope the solver is allowed to fill
-- ---------------------------------------------------------------------------

create table user_settings (
  user_id                    uuid primary key references auth.users (id) on delete cascade,

  -- Sleep is Tier 1 by default. Directive: protect sleep.
  sleep_start                time    not null default '23:00',
  sleep_end                  time    not null default '07:00',
  sleep_protected            boolean not null default true,

  -- The window the solver may place work in (further narrowed by events).
  day_start                  time    not null default '07:30',
  day_end                    time    not null default '22:30',

  max_daily_focus_min        int     not null default 300
                               check (max_daily_focus_min between 0 and 1440),
  min_block_min              int     not null default 25  check (min_block_min >= 5),
  max_block_min              int     not null default 120,
  context_switch_penalty_min int     not null default 10  check (context_switch_penalty_min >= 0),
  planning_horizon_days      int     not null default 21
                               check (planning_horizon_days between 1 and 120),

  created_at                 timestamptz not null default now(),
  updated_at                 timestamptz not null default now(),

  constraint block_bounds_ordered check (max_block_min >= min_block_min)
);

create trigger user_settings_updated_at
  before update on user_settings
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- energy_profile — 168 rows per user (day-of-week x hour).
-- Seeded from onboarding, then learned from time_entries (migration 003).
-- multiplier 1.00 = baseline; 1.30 = peak cognition; 0.40 = post-lunch trough.
-- ---------------------------------------------------------------------------

create table energy_profile (
  user_id    uuid     not null references auth.users (id) on delete cascade,
  dow        smallint not null check (dow between 0 and 6),   -- 0 = Sunday
  hour       smallint not null check (hour between 0 and 23),
  multiplier numeric(3, 2) not null default 1.00
               check (multiplier >= 0 and multiplier <= 2),
  samples    int      not null default 0,
  updated_at timestamptz not null default now(),
  primary key (user_id, dow, hour)
);

-- ---------------------------------------------------------------------------
-- calendars
-- ---------------------------------------------------------------------------

create type calendar_provider as enum ('local', 'google', 'notion');

create table calendars (
  id                   uuid primary key default gen_random_uuid(),
  user_id              uuid not null references auth.users (id) on delete cascade,
  name                 text not null,
  provider             calendar_provider not null default 'local',
  provider_calendar_id text,
  color_token          text    not null default 'neutral',
  is_visible           boolean not null default true,

  -- Read/write posture toward the remote provider.
  is_writable          boolean not null default true,
  -- Exactly one calendar per user is app-managed. The Google sync layer is
  -- only ever permitted to CREATE/UPDATE/DELETE events on that calendar;
  -- every other calendar is strictly read-only unless the user opts in.
  is_app_managed       boolean not null default false,

  created_at           timestamptz not null default now(),
  updated_at           timestamptz not null default now(),

  unique (user_id, provider, provider_calendar_id)
);

create unique index calendars_one_app_managed
  on calendars (user_id)
  where is_app_managed;

create trigger calendars_updated_at
  before update on calendars
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- subjects — IB subjects plus the core (EE / TOK / CAS)
-- ---------------------------------------------------------------------------

create type ib_level as enum ('HL', 'SL', 'CORE');

create table subjects (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  name         text not null,
  -- Null for core components (EE, TOK, CAS), which have no IB group.
  ib_group     smallint check (ib_group between 1 and 6),
  level        ib_level not null,
  teacher      text,
  color_token  text not null default 'neutral',
  -- Relative weight toward the final grade; feeds the solver's priority term.
  grade_weight numeric(4, 2) not null default 1.00 check (grade_weight >= 0),
  is_archived  boolean not null default false,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now(),

  unique (user_id, name),
  constraint core_has_no_group check (
    (level = 'CORE' and ib_group is null) or (level <> 'CORE' and ib_group is not null)
  )
);

create trigger subjects_updated_at
  before update on subjects
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table profiles       enable row level security;
alter table user_settings  enable row level security;
alter table energy_profile enable row level security;
alter table calendars      enable row level security;
alter table subjects       enable row level security;

create policy profiles_owner on profiles
  for all using (auth.uid() = id) with check (auth.uid() = id);

create policy user_settings_owner on user_settings
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy energy_profile_owner on energy_profile
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy calendars_owner on calendars
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy subjects_owner on subjects
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- New-user bootstrap: profile + settings + a flat 168-slot energy curve.
-- The curve is deliberately flat here; onboarding shapes it, then the
-- calibration job in migration 003 learns the real one from tracked time.
-- ---------------------------------------------------------------------------

create or replace function handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into profiles (id, display_name)
    values (new.id, coalesce(new.raw_user_meta_data ->> 'full_name', ''))
    on conflict (id) do nothing;

  insert into user_settings (user_id) values (new.id)
    on conflict (user_id) do nothing;

  insert into energy_profile (user_id, dow, hour)
    select new.id, d, h
    from generate_series(0, 6) as d, generate_series(0, 23) as h
    on conflict do nothing;

  insert into calendars (user_id, name, provider, is_app_managed, color_token)
    values (new.id, 'IB Calendar OS', 'local', true, 'primary');

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- ─────────── 002_time_entities.sql ───────────
-- ============================================================================
-- 002_time_entities.sql
--
-- The central modelling decision of this system lives here:
--
--   events            fixed in time. The solver reads them, never writes them.
--   tasks             have duration + deadline but NO position. Flexible.
--   scheduled_blocks  the solver's output. The join between task and timeline.
--   schedule_runs     an immutable ledger of solver generations.
--
-- Because solver output is versioned rather than mutated in place, three
-- product features collapse into one mechanism:
--   "Reset Day"        -> a new run scoped to a single day
--   "What-If branch"   -> a run with parent_run_id and is_active = false
--   "Undo"             -> flip is_active back to the previous run
-- ============================================================================

-- ---------------------------------------------------------------------------
-- events — Tier 1 & 2 reality. Classes, exams, appointments, sleep.
-- ---------------------------------------------------------------------------

create type event_kind as enum (
  'class', 'exam', 'appointment', 'sleep', 'commitment', 'travel', 'general'
);

create table events (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  calendar_id uuid references calendars (id) on delete cascade,
  subject_id  uuid references subjects (id) on delete set null,

  title       text not null,
  description text,
  location    text,

  starts_at   timestamptz not null,
  ends_at     timestamptz not null,
  span        tstzrange generated always as (tstzrange(starts_at, ends_at, '[)')) stored,

  -- Constraint hierarchy. 1 = immutable, 5 = recovery (first to be sacrificed).
  tier        smallint not null default 2 check (tier between 1 and 5),
  kind        event_kind not null default 'general',

  -- User-pinned. Never moved regardless of tier.
  is_locked   boolean not null default false,
  all_day     boolean not null default false,
  rrule       text,

  source      text not null default 'local',
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint events_ordered check (ends_at > starts_at)
);

-- Directive #3, enforced at the storage layer rather than trusted to
-- application code: two immutable commitments can never occupy the same
-- instant. An exam colliding with a class is a data error, not a UI warning.
alter table events add constraint events_no_tier1_overlap
  exclude using gist (user_id with =, span with &&)
  where (tier = 1 and not all_day);

create index events_user_starts_idx on events (user_id, starts_at);
create index events_span_idx        on events using gist (user_id, span);
create index events_calendar_idx    on events (calendar_id);

create trigger events_updated_at
  before update on events
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- assessments — the IB artefacts that generate most of the workload
-- ---------------------------------------------------------------------------

create type assessment_kind as enum (
  'ia_draft', 'ia_final', 'ee_draft', 'ee_final',
  'tok_essay', 'tok_exhibition', 'cas_reflection',
  'mock', 'paper', 'oral', 'test', 'other'
);

create table assessments (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  subject_id   uuid references subjects (id) on delete cascade,

  kind         assessment_kind not null,
  title        text not null,
  due_at       timestamptz,
  -- Percentage of the subject's final grade. Feeds the solver priority term.
  grade_weight numeric(5, 2) not null default 0 check (grade_weight >= 0),
  -- External = IB-submitted. These deadlines are never negotiable.
  is_external  boolean not null default false,
  status       text not null default 'open'
                 check (status in ('open', 'submitted', 'graded', 'cancelled')),

  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index assessments_user_due_idx on assessments (user_id, due_at)
  where status = 'open';

create trigger assessments_updated_at
  before update on assessments
  for each row execute function set_updated_at();

-- ---------------------------------------------------------------------------
-- tasks — the schedulable unit. Duration without position.
-- ---------------------------------------------------------------------------

create type task_status as enum ('todo', 'in_progress', 'blocked', 'done', 'dropped');

create table tasks (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users (id) on delete cascade,
  subject_id        uuid references subjects (id) on delete set null,
  assessment_id     uuid references assessments (id) on delete set null,
  parent_task_id    uuid references tasks (id) on delete cascade,

  title             text not null,
  notes             text,

  estimate_min      int not null default 60 check (estimate_min > 0),
  -- Set from estimate_min on insert by the trigger below; decremented as
  -- time_entries land. The solver schedules remaining_min, never estimate_min.
  remaining_min     int not null default 0 check (remaining_min >= 0),
  actual_min        int not null default 0 check (actual_min >= 0),

  deadline_at       timestamptz,
  earliest_start_at timestamptz,

  cognitive_load    smallint not null default 3 check (cognitive_load between 1 and 5),

  -- Splittable tasks may be chunked across blocks; an exam rehearsal may not.
  splittable        boolean not null default true,
  min_chunk_min     int not null default 25 check (min_chunk_min >= 5),
  max_chunk_min     int not null default 120,

  status            task_status not null default 'todo',
  -- User override. 0 = none, 3 = "this is the only thing that matters today".
  priority_pin      smallint not null default 0 check (priority_pin between 0 and 3),
  completed_at      timestamptz,

  created_at        timestamptz not null default now(),
  updated_at        timestamptz not null default now(),

  constraint chunk_bounds_ordered check (max_chunk_min >= min_chunk_min),
  constraint remaining_within_estimate check (remaining_min <= estimate_min),
  constraint window_ordered check (
    earliest_start_at is null or deadline_at is null or earliest_start_at < deadline_at
  ),
  constraint no_self_parent check (parent_task_id is null or parent_task_id <> id)
);

create or replace function tasks_seed_remaining()
returns trigger
language plpgsql
as $$
begin
  if tg_op = 'INSERT' and new.remaining_min = 0 and new.status <> 'done' then
    new.remaining_min = new.estimate_min;
  end if;
  if new.status = 'done' then
    new.remaining_min = 0;
    new.completed_at = coalesce(new.completed_at, now());
  end if;
  return new;
end;
$$;

create trigger tasks_seed_remaining_trg
  before insert or update on tasks
  for each row execute function tasks_seed_remaining();

create trigger tasks_updated_at
  before update on tasks
  for each row execute function set_updated_at();

-- Partial index: the solver only ever loads unfinished work.
create index tasks_open_deadline_idx on tasks (user_id, deadline_at)
  where status in ('todo', 'in_progress', 'blocked');
create index tasks_subject_idx    on tasks (subject_id);
create index tasks_assessment_idx on tasks (assessment_id);

-- ---------------------------------------------------------------------------
-- task_dependencies — the DAG
-- ---------------------------------------------------------------------------

create type dependency_type as enum ('FS', 'SS', 'FF');  -- finish-start, start-start, finish-finish

create table task_dependencies (
  user_id        uuid not null references auth.users (id) on delete cascade,
  predecessor_id uuid not null references tasks (id) on delete cascade,
  successor_id   uuid not null references tasks (id) on delete cascade,
  dep_type       dependency_type not null default 'FS',
  lag_min        int not null default 0,
  created_at     timestamptz not null default now(),

  primary key (predecessor_id, successor_id),
  constraint no_self_dependency check (predecessor_id <> successor_id)
);

create index task_dependencies_successor_idx on task_dependencies (successor_id);
create index task_dependencies_user_idx      on task_dependencies (user_id);

-- Acyclicity is enforced here rather than in the solver. A cycle that reaches
-- the topological sort is an infinite loop or a silently dropped edge; a cycle
-- rejected at write time is an error message pointing at one bad edge.
-- The graph is small (hundreds of nodes), so the reachability probe is cheap.
create or replace function assert_task_dag_acyclic()
returns trigger
language plpgsql
as $$
declare
  closes_cycle boolean;
begin
  with recursive reachable (id) as (
    select new.successor_id
    union
    select d.successor_id
      from task_dependencies d
      join reachable r on d.predecessor_id = r.id
  )
  select exists (select 1 from reachable where id = new.predecessor_id)
    into closes_cycle;

  if closes_cycle then
    raise exception
      'Dependency cycle: task % cannot depend on % (it is already downstream)',
      new.successor_id, new.predecessor_id
      using errcode = 'check_violation';
  end if;

  return new;
end;
$$;

create constraint trigger task_dependencies_acyclic
  after insert or update on task_dependencies
  deferrable initially immediate
  for each row execute function assert_task_dag_acyclic();

-- ---------------------------------------------------------------------------
-- schedule_runs — the immutable solver ledger
-- ---------------------------------------------------------------------------

create table schedule_runs (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade,
  -- Non-null => this run is a what-if branch off another run.
  parent_run_id  uuid references schedule_runs (id) on delete set null,

  horizon_start  timestamptz not null,
  horizon_end    timestamptz not null,

  -- Hash of the frozen solver input. Identical hash + identical seed must
  -- produce identical output; re-solving a matching hash short-circuits.
  input_hash     text   not null,
  strategy       text   not null default 'default',
  seed           bigint not null default 0,

  status         text not null default 'draft'
                   check (status in ('draft', 'active', 'superseded', 'discarded')),
  is_active      boolean not null default false,

  -- Tasks that could NOT be placed, with shortfall + blocking constraint +
  -- ranked remedies. Never empty-and-silent: unplaceable work is surfaced.
  infeasibility  jsonb not null default '[]'::jsonb,
  stats          jsonb not null default '{}'::jsonb,
  label          text,

  created_at     timestamptz not null default now(),

  constraint horizon_ordered check (horizon_end > horizon_start)
);

-- At most one active schedule per user. This is what makes "undo" safe.
create unique index schedule_runs_single_active
  on schedule_runs (user_id)
  where is_active;

create index schedule_runs_user_created_idx on schedule_runs (user_id, created_at desc);
create index schedule_runs_parent_idx       on schedule_runs (parent_run_id);

-- ---------------------------------------------------------------------------
-- scheduled_blocks — solver output
-- ---------------------------------------------------------------------------

create table scheduled_blocks (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade,
  run_id         uuid not null references schedule_runs (id) on delete cascade,
  task_id        uuid not null references tasks (id) on delete cascade,

  starts_at      timestamptz not null,
  ends_at        timestamptz not null,
  span           tstzrange generated always as (tstzrange(starts_at, ends_at, '[)')) stored,

  sequence_index int not null default 0,
  -- A locked block survives re-solves untouched and is carried into new runs.
  is_locked      boolean not null default false,
  -- energy_profile.multiplier at placement time; powers the "why here?" UI.
  energy_score   numeric(5, 2),

  created_at     timestamptz not null default now(),

  constraint blocks_ordered check (ends_at > starts_at)
);

-- Blocks may overlap ACROSS runs — that is the whole point of what-if
-- branching — but never WITHIN a run. Scoping the exclusion to run_id gets
-- both properties from one constraint.
alter table scheduled_blocks add constraint blocks_no_overlap_within_run
  exclude using gist (run_id with =, span with &&);

create index blocks_run_starts_idx on scheduled_blocks (run_id, starts_at);
create index blocks_task_idx       on scheduled_blocks (task_id);
create index blocks_span_idx       on scheduled_blocks using gist (user_id, span);

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table events            enable row level security;
alter table assessments       enable row level security;
alter table tasks             enable row level security;
alter table task_dependencies enable row level security;
alter table schedule_runs     enable row level security;
alter table scheduled_blocks  enable row level security;

create policy events_owner on events
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy assessments_owner on assessments
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy tasks_owner on tasks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy task_dependencies_owner on task_dependencies
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy schedule_runs_owner on schedule_runs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy scheduled_blocks_owner on scheduled_blocks
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Atomic run activation. Flipping the active generation must be all-or-nothing
-- or the unique partial index above will reject the second write and leave the
-- user with no active schedule at all.
-- ---------------------------------------------------------------------------

create or replace function activate_schedule_run(p_run_id uuid)
returns void
language plpgsql
security invoker
as $$
declare
  v_user uuid;
begin
  select user_id into v_user from schedule_runs where id = p_run_id;
  if v_user is null then
    raise exception 'schedule run % not found', p_run_id;
  end if;

  update schedule_runs
     set is_active = false, status = 'superseded'
   where user_id = v_user and is_active and id <> p_run_id;

  update schedule_runs
     set is_active = true, status = 'active'
   where id = p_run_id;
end;
$$;

-- ─────────── 003_telemetry_sync_ai.sql ───────────
-- ============================================================================
-- 003_telemetry_sync_ai.sql
--
-- Three concerns that are cheap now and near-impossible to retrofit later:
--   1. time_entries / estimation_calibration — the loop that makes estimates
--      true instead of hopeful.
--   2. sync_mappings / sync_state — without stored (local, remote, etag, hash)
--      triples, two-way Google sync duplicates events and echoes forever.
--   3. ai_proposals — the physical boundary that makes "the LLM never writes
--      to the database" an architectural fact rather than a good intention.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- time_entries — ground truth for how long things actually take
-- ---------------------------------------------------------------------------

create table time_entries (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  task_id    uuid references tasks (id) on delete cascade,
  block_id   uuid references scheduled_blocks (id) on delete set null,

  started_at timestamptz not null,
  ended_at   timestamptz,
  -- Denormalised on close so analytics never re-derive it from timestamps.
  duration_min int,

  source     text not null default 'timer'
               check (source in ('timer', 'manual', 'inferred')),
  note       text,
  created_at timestamptz not null default now(),

  constraint entry_ordered check (ended_at is null or ended_at > started_at)
);

create index time_entries_task_idx      on time_entries (task_id);
create index time_entries_user_date_idx on time_entries (user_id, started_at desc);
-- At most one running timer per user.
create unique index time_entries_one_open on time_entries (user_id)
  where ended_at is null;

-- Closing an entry rolls the minutes into the task. Doing this in a trigger
-- keeps tasks.actual_min consistent no matter which client wrote the entry.
create or replace function time_entries_apply()
returns trigger
language plpgsql
as $$
declare
  v_minutes int;
begin
  if new.ended_at is null then
    return new;
  end if;

  v_minutes := greatest(0, floor(extract(epoch from (new.ended_at - new.started_at)) / 60)::int);
  new.duration_min := v_minutes;

  if new.task_id is not null and (tg_op = 'INSERT' or old.ended_at is null) then
    update tasks
       set actual_min    = actual_min + v_minutes,
           remaining_min = greatest(0, remaining_min - v_minutes)
     where id = new.task_id;
  end if;

  return new;
end;
$$;

create trigger time_entries_apply_trg
  before insert or update on time_entries
  for each row execute function time_entries_apply();

-- ---------------------------------------------------------------------------
-- estimation_calibration — learned estimate:actual ratios.
-- After ~20 samples the empirical p80 outranks the model's guess.
-- ---------------------------------------------------------------------------

create table estimation_calibration (
  user_id        uuid not null references auth.users (id) on delete cascade,
  subject_id     uuid references subjects (id) on delete cascade,
  cognitive_load smallint not null check (cognitive_load between 1 and 5),

  ratio_p50      numeric(5, 2) not null default 1.00,
  ratio_p80      numeric(5, 2) not null default 1.00,
  n_samples      int not null default 0,
  updated_at     timestamptz not null default now(),

  primary key (user_id, subject_id, cognitive_load)
);

-- ---------------------------------------------------------------------------
-- momentum_snapshots — rolling 7-day health. Explicitly NOT a streak:
-- there is no counter that can reset to zero and no all-or-nothing day.
-- ---------------------------------------------------------------------------

create type momentum_state as enum ('thriving', 'steady', 'strained', 'recovering');

create table momentum_snapshots (
  user_id        uuid not null references auth.users (id) on delete cascade,
  day            date not null,
  planned_min    int  not null default 0,
  completed_min  int  not null default 0,
  rolling7_ratio numeric(4, 3) not null default 0,
  state          momentum_state not null default 'steady',
  created_at     timestamptz not null default now(),
  primary key (user_id, day)
);

-- ---------------------------------------------------------------------------
-- retrospectives — end-of-day review
-- ---------------------------------------------------------------------------

create table retrospectives (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  day        date not null,
  wins       jsonb not null default '[]'::jsonb,
  friction   jsonb not null default '[]'::jsonb,
  carryover  jsonb not null default '[]'::jsonb,
  energy_rating smallint check (energy_rating between 1 and 5),
  note       text,
  created_at timestamptz not null default now(),
  unique (user_id, day)
);

-- ---------------------------------------------------------------------------
-- themes — Pinterest-inspired theme engine.
-- Tokens are semantic (studying, exam, rest), never raw hex at the call site:
-- the solver marks a block by MEANING and the theme decides pixels.
-- ---------------------------------------------------------------------------

create table themes (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  name             text not null,
  tokens           jsonb not null default '{}'::jsonb,
  source_image_url text,
  is_active        boolean not null default false,
  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),
  unique (user_id, name)
);

create unique index themes_one_active on themes (user_id) where is_active;

-- ---------------------------------------------------------------------------
-- Integration sync state
-- ---------------------------------------------------------------------------

create table sync_state (
  user_id             uuid not null references auth.users (id) on delete cascade,
  provider            calendar_provider not null,
  -- Google incremental syncToken / Notion cursor.
  sync_token          text,
  cursor              text,
  -- Push-notification channel; renewed proactively before expiry.
  channel_id          text,
  channel_resource_id text,
  channel_expires_at  timestamptz,
  last_full_sync_at   timestamptz,
  last_error          text,
  updated_at          timestamptz not null default now(),
  primary key (user_id, provider)
);

create index sync_state_channel_expiry_idx on sync_state (channel_expires_at)
  where channel_expires_at is not null;

create table sync_mappings (
  id            uuid primary key default gen_random_uuid(),
  user_id       uuid not null references auth.users (id) on delete cascade,
  provider      calendar_provider not null,
  local_table   text not null,
  local_id      uuid not null,
  remote_id     text not null,
  remote_etag   text,
  -- Hash of the canonical local payload. Inbound change with a matching hash
  -- is our own write echoing back and must be dropped, or the two systems
  -- will ping-pong updates at each other indefinitely.
  content_hash  text,
  last_synced_at timestamptz not null default now(),

  unique (user_id, provider, remote_id),
  unique (user_id, provider, local_table, local_id)
);

create index sync_mappings_local_idx on sync_mappings (local_table, local_id);

-- ---------------------------------------------------------------------------
-- ai_proposals — the AI safety boundary.
--
-- Directive #2: an opaque model never mutates database state. Every model
-- output lands HERE as a typed, Zod-validated proposal. A separate
-- deterministic applier turns approved proposals into real writes.
-- There is no code path from model output to a table write that skips this.
-- ---------------------------------------------------------------------------

create type proposal_kind as enum (
  'task_extract',      -- parse a syllabus/page into candidate tasks
  'estimate',          -- suggest estimate_min
  'classify',          -- subject / cognitive_load / tier
  'dependency',        -- suggest DAG edges
  'reschedule_intent', -- NL request -> structured solver invocation
  'summarize'
);

create type proposal_status as enum (
  'pending', 'auto_approved', 'approved', 'rejected', 'applied', 'invalid'
);

create table ai_proposals (
  id                uuid primary key default gen_random_uuid(),
  user_id           uuid not null references auth.users (id) on delete cascade,

  kind              proposal_kind   not null,
  status            proposal_status not null default 'pending',
  payload           jsonb           not null,

  model             text,
  confidence        numeric(4, 3) check (confidence between 0 and 1),

  -- Provenance of the INPUT. Content arriving from a syllabus PDF, a Notion
  -- page or a calendar description is untrusted: instruction-shaped text
  -- inside it is data to be shown to the user, never commands to execute.
  source_kind       text not null default 'user'
                      check (source_kind in ('user', 'pdf', 'notion', 'google', 'system')),
  source_ref        text,
  is_trusted_source boolean not null default false,

  -- Populated when the Zod schema rejects the model output. A proposal that
  -- fails validation is marked 'invalid' and is never partially applied.
  validation_errors jsonb,

  -- Destructive or Tier-1-touching proposals require explicit confirmation
  -- regardless of confidence.
  requires_confirmation boolean not null default true,

  applied_run_id    uuid references schedule_runs (id) on delete set null,
  applied_at        timestamptz,
  created_at        timestamptz not null default now()
);

create index ai_proposals_pending_idx on ai_proposals (user_id, created_at desc)
  where status in ('pending', 'auto_approved');

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table time_entries           enable row level security;
alter table estimation_calibration enable row level security;
alter table momentum_snapshots     enable row level security;
alter table retrospectives         enable row level security;
alter table themes                 enable row level security;
alter table sync_state             enable row level security;
alter table sync_mappings          enable row level security;
alter table ai_proposals           enable row level security;

create policy time_entries_owner on time_entries
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy estimation_calibration_owner on estimation_calibration
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy momentum_snapshots_owner on momentum_snapshots
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy retrospectives_owner on retrospectives
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy themes_owner on themes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Sync internals are service-role only: they hold provider cursors and
-- channel identifiers that no browser session has any reason to read.
create policy sync_state_owner_read on sync_state
  for select using (auth.uid() = user_id);

create policy sync_mappings_owner_read on sync_mappings
  for select using (auth.uid() = user_id);

create policy ai_proposals_owner on ai_proposals
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ─────────── 004_integration_accounts.sql ───────────
-- ============================================================================
-- 004_integration_accounts.sql
--
-- OAuth credentials for connected providers.
--
-- SECURITY POSTURE: this table has RLS enabled and NO policy granting access.
-- That is deliberate, not an oversight — with RLS on and no policy, every
-- browser session (anon and authenticated alike) reads zero rows. Only the
-- service-role client, used exclusively by server-side sync jobs and webhook
-- handlers, can touch it. A refresh token is a long-lived key to the user's
-- entire calendar; it should never be reachable from a page.
-- ============================================================================

create table integration_accounts (
  id               uuid primary key default gen_random_uuid(),
  user_id          uuid not null references auth.users (id) on delete cascade,
  provider         calendar_provider not null,

  provider_user_id text,
  provider_email   text,

  access_token     text,
  refresh_token    text,
  token_expires_at timestamptz,
  scopes           text[] not null default '{}',

  -- Set when the provider rejects our refresh token (revoked access, password
  -- change). The UI prompts a reconnect instead of retrying forever.
  needs_reauth     boolean not null default false,
  last_error       text,

  created_at       timestamptz not null default now(),
  updated_at       timestamptz not null default now(),

  unique (user_id, provider)
);

create trigger integration_accounts_updated_at
  before update on integration_accounts
  for each row execute function set_updated_at();

alter table integration_accounts enable row level security;
-- Intentionally no policies. See the note at the top of this file.

-- ---------------------------------------------------------------------------
-- Sync bookkeeping the pull loop needs but 003 did not anticipate.
-- ---------------------------------------------------------------------------

alter table sync_state
  add column if not exists sync_in_progress boolean not null default false,
  add column if not exists consecutive_failures int not null default 0;

-- A Google event we deleted locally must be remembered long enough for the
-- next incremental pull to not resurrect it. Deleting the mapping outright
-- would make the event look brand new on the following sync.
alter table sync_mappings
  add column if not exists deleted_locally boolean not null default false;

create index if not exists sync_mappings_pending_delete_idx
  on sync_mappings (user_id, provider)
  where deleted_locally;

-- ─────────── 005_context_hydration.sql ───────────
-- ============================================================================
-- 005_context_hydration.sql
--
-- Roadmap step 20. Lets a task carry a pointer to wherever the work actually
-- lives — an Obsidian note, a Google Doc, a repository path — so entering
-- focus mode opens the context instead of making the student go find it.
--
-- Stored as a URI rather than a file path so obsidian://, vscode:// and
-- https:// are all expressible without a separate type column.
-- ============================================================================

alter table tasks
  add column if not exists context_uri text,
  add column if not exists context_label text;

-- Reject anything that isn't a URI we are prepared to hand to the browser.
-- javascript: and data: URIs in particular must never reach an href.
alter table tasks add constraint tasks_context_uri_scheme check (
  context_uri is null
  or context_uri ~* '^(https?|obsidian|vscode|file|notion|zotero)://'
);

alter table user_settings
  add column if not exists focus_hides_navigation boolean not null default true,
  add column if not exists focus_autostart_timer boolean not null default true;

-- ─────────── 006_academic_calendar.sql ───────────
-- ============================================================================
-- 006_academic_calendar.sql
--
-- The school year's fixed landmarks: exam sessions, terms, half terms.
--
-- These are deliberately NOT rows in `events`. An event occupies time on the
-- grid and the solver schedules around it; a term boundary is a *date*, has no
-- clock time, often spans weeks, and exists to give the student orientation
-- rather than to block out hours. Modelling them as events would put a
-- three-week holiday on the calendar as an all-day blocker and quietly delete
-- half the study capacity in the horizon.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Prerequisite check.
--
-- Without this, running out of order (or against the wrong project) fails
-- with a bare "relation \"subjects\" does not exist", which says nothing about
-- the actual cause. Fail loudly and usefully instead.
-- ---------------------------------------------------------------------------
do $guard$
begin
  if to_regclass('public.subjects') is null
     or to_regproc('public.set_updated_at') is null then
    raise exception
      'Migration 006 cannot run: migrations 001-005 are not present in this database. Either run supabase/FULL_SCHEMA.sql on a fresh project, or check you are connected to the right Supabase project (this app expects the one holding your existing subjects and tasks).';
  end if;
end
$guard$;


create type academic_date_kind as enum (
  'exam_session',   -- the IB session itself — the year's anchor
  'mock_exams',
  'term_start',
  'term_end',
  'half_term',      -- the break, start..end
  'holiday',
  'coursework_deadline'
);

create table academic_dates (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,

  kind       academic_date_kind not null,
  label      text not null,

  -- Dates, not timestamps. A term does not start at 09:00 in a timezone; it
  -- starts on a day. Keeping this a `date` avoids an entire class of
  -- off-by-one-at-midnight bugs when counting days remaining.
  starts_on  date not null,
  -- Null for single-day landmarks; set for ranges (half terms, exam windows).
  ends_on    date,

  -- Exactly one landmark per user is the year's anchor — the countdown that
  -- gets top billing. Usually the IB exam session.
  is_primary boolean not null default false,

  notes      text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint academic_range_ordered check (ends_on is null or ends_on >= starts_on)
);

create unique index academic_dates_one_primary
  on academic_dates (user_id)
  where is_primary;

create index academic_dates_user_start_idx on academic_dates (user_id, starts_on);

create trigger academic_dates_updated_at
  before update on academic_dates
  for each row execute function set_updated_at();

alter table academic_dates enable row level security;

create policy academic_dates_owner on academic_dates
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Subject weighting becomes meaningful.
--
-- subjects.grade_weight already feeds the solver's priority term, but nothing
-- ever set it: onboarding left every subject at 1.0, so the weighting was
-- inert. Recording the intent here so the UI can expose it.
-- ---------------------------------------------------------------------------

comment on column subjects.grade_weight is
  'Relative importance of this subject, 0.5 = coasting, 1.0 = normal, 2.0 = the one that decides the offer. Feeds the solver priority weight.';

-- ─────────── 007_timetable.sql ───────────
-- ============================================================================
-- 007_timetable.sql
--
-- The recurring school timetable.
--
-- Until now nothing in the app could create a class. `events` had exactly two
-- writers — Google sync and nothing else — so a student without Google
-- credentials had a solver that believed every weekday was completely free
-- and would happily schedule revision on top of a double Physics lesson.
--
-- Stored as a weekly PATTERN, not as expanded rows. Materialising a year of
-- lessons into `events` would mean thousands of rows to keep in step every
-- time a period moves, and a "delete this lesson" that silently diverges from
-- the pattern. The pattern is expanded on read instead (see
-- src/lib/scheduling/timetable.ts), so there is one source of truth.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Prerequisite check.
--
-- Without this, running out of order (or against the wrong project) fails
-- with a bare "relation \"subjects\" does not exist", which says nothing about
-- the actual cause. Fail loudly and usefully instead.
-- ---------------------------------------------------------------------------
do $guard$
begin
  if to_regclass('public.subjects') is null
     or to_regproc('public.set_updated_at') is null then
    raise exception
      'Migration 007 cannot run: migrations 001-005 are not present in this database. Either run supabase/FULL_SCHEMA.sql on a fresh project, or check you are connected to the right Supabase project (this app expects the one holding your existing subjects and tasks).';
  end if;
end
$guard$;


-- Many IB schools run a two-week cycle. Modelling only 'every' would force
-- students on a fortnightly timetable to enter the wrong schedule.
create type week_parity as enum ('every', 'A', 'B');

create table timetable_entries (
  id          uuid primary key default gen_random_uuid(),
  user_id     uuid not null references auth.users (id) on delete cascade,
  subject_id  uuid references subjects (id) on delete set null,

  -- Free text so non-teaching fixtures (registration, games, orchestra) can
  -- live in the timetable without pretending to be an IB subject.
  label       text not null,
  room        text,

  day_of_week smallint not null check (day_of_week between 0 and 6), -- 0 = Sunday
  -- Minutes from local midnight. Same integer-minute convention as the solver.
  starts_min  smallint not null check (starts_min between 0 and 1439),
  ends_min    smallint not null check (ends_min between 1 and 1440),

  parity      week_parity not null default 'every',

  -- A timetable changes between terms. Null active_to means "still current".
  active_from date,
  active_to   date,

  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),

  constraint timetable_times_ordered check (ends_min > starts_min),
  constraint timetable_dates_ordered check (
    active_from is null or active_to is null or active_to >= active_from
  )
);

create index timetable_entries_user_day_idx
  on timetable_entries (user_id, day_of_week, starts_min);

create trigger timetable_entries_updated_at
  before update on timetable_entries
  for each row execute function set_updated_at();

alter table timetable_entries enable row level security;

create policy timetable_entries_owner on timetable_entries
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Which real-world week counts as "Week A".
--
-- Parity is meaningless without an anchor: 'A' only identifies a week
-- relative to a known starting Monday. Null means the student is on a simple
-- one-week timetable and every entry applies.
-- ---------------------------------------------------------------------------

alter table user_settings
  add column timetable_anchor_monday date;

comment on column user_settings.timetable_anchor_monday is
  'Monday of a known Week A. Null = single-week timetable, parity ignored.';

-- ─────────── 008_study_quotas.sql ───────────
-- ============================================================================
-- 008_study_quotas.sql
--
-- Recurring weekly study commitments: "3h of SAT Maths every week, forever."
--
-- The app could previously only express one-off work with a deadline, which
-- is the wrong shape for SAT, TOPIK or language drilling. Those have no due
-- date and never finish — they are a rate, not a task.
--
-- DESIGN: a quota is a TEMPLATE that materialises one real `tasks` row per
-- week, rather than a synthetic item the solver invents on the fly. Real rows
-- mean timers, completion, estimate calibration and the DAG all work on quota
-- work exactly as they do on everything else, with no parallel code path.
--
-- Deliberately NOT topic-planned. The quota protects the hours; what gets
-- studied inside them is decided at the desk. Pre-planning "Week 7: quadratic
-- inequalities" in September is a fiction that survives contact with reality
-- for about a fortnight.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Prerequisite check.
--
-- Without this, running out of order (or against the wrong project) fails
-- with a bare "relation \"subjects\" does not exist", which says nothing about
-- the actual cause. Fail loudly and usefully instead.
-- ---------------------------------------------------------------------------
do $guard$
begin
  if to_regclass('public.subjects') is null
     or to_regproc('public.set_updated_at') is null then
    raise exception
      'Migration 008 cannot run: migrations 001-005 are not present in this database. Either run supabase/FULL_SCHEMA.sql on a fresh project, or check you are connected to the right Supabase project (this app expects the one holding your existing subjects and tasks).';
  end if;
end
$guard$;


create table study_quotas (
  id              uuid primary key default gen_random_uuid(),
  user_id         uuid not null references auth.users (id) on delete cascade,
  subject_id      uuid references subjects (id) on delete set null,

  label           text not null,
  target_min_week int  not null check (target_min_week between 15 and 3000),

  -- Chunking preferences. Weak areas want frequency over duration, so the
  -- default session is short enough to schedule several times a week.
  min_session_min int not null default 30 check (min_session_min >= 10),
  max_session_min int not null default 90,

  cognitive_load  smallint not null default 3 check (cognitive_load between 1 and 5),
  -- Same 0-3 scale as tasks.priority_pin.
  priority_pin    smallint not null default 0 check (priority_pin between 0 and 3),

  is_active       boolean not null default true,
  active_from     date,
  active_to       date,

  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),

  constraint quota_session_bounds check (max_session_min >= min_session_min),
  constraint quota_dates_ordered check (
    active_from is null or active_to is null or active_to >= active_from
  )
);

create index study_quotas_user_active_idx on study_quotas (user_id) where is_active;

create trigger study_quotas_updated_at
  before update on study_quotas
  for each row execute function set_updated_at();

alter table study_quotas enable row level security;

create policy study_quotas_owner on study_quotas
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Link generated tasks back to their quota.
--
-- quota_week is the Monday of the week the task covers. The unique index is
-- what makes generation idempotent: running the generator twice, or from two
-- devices at once, cannot produce duplicate SAT Maths blocks for one week.
-- ---------------------------------------------------------------------------

alter table tasks
  add column quota_id   uuid references study_quotas (id) on delete cascade,
  add column quota_week date;

create unique index tasks_one_per_quota_week
  on tasks (quota_id, quota_week)
  where quota_id is not null;

alter table tasks add constraint quota_week_present check (
  (quota_id is null and quota_week is null) or
  (quota_id is not null and quota_week is not null)
);

comment on column tasks.quota_week is
  'Monday of the week this quota task covers. Null for ordinary one-off tasks.';

-- ─────────── 009_day_write_offs.sql ───────────
-- ============================================================================
-- 009_day_write_offs.sql
--
-- "I was ill on Tuesday."
--
-- Without this a lost day silently becomes an overdue pile: the plan still
-- says work happened, the momentum ratio counts the miss, and the student
-- opens the app to a backlog and a number telling them they are failing.
-- Illness is not a discipline problem and the app should not score it as one.
--
-- Writing a day off does three things, all of them consequences of this one
-- row: the solver treats the day as zero capacity, momentum treats it as a
-- rest day rather than a miss, and the work is redistributed on the next
-- solve.
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Prerequisite check.
--
-- Without this, running out of order (or against the wrong project) fails
-- with a bare "relation \"subjects\" does not exist", which says nothing about
-- the actual cause. Fail loudly and usefully instead.
-- ---------------------------------------------------------------------------
do $guard$
begin
  if to_regclass('public.subjects') is null
     or to_regproc('public.set_updated_at') is null then
    raise exception
      'Migration 009 cannot run: migrations 001-005 are not present in this database. Either run supabase/FULL_SCHEMA.sql on a fresh project, or check you are connected to the right Supabase project (this app expects the one holding your existing subjects and tasks).';
  end if;
end
$guard$;


create type write_off_reason as enum ('illness', 'family', 'travel', 'burnout', 'other');

create table day_write_offs (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,

  -- A local calendar date, not an instant. "Tuesday" is a day in the
  -- student's timezone, not a 24-hour window from some UTC moment.
  day        date not null,
  reason     write_off_reason not null default 'illness',
  note       text,

  created_at timestamptz not null default now(),

  -- Writing a day off twice is a no-op, not two write-offs.
  unique (user_id, day)
);

create index day_write_offs_user_day_idx on day_write_offs (user_id, day desc);

alter table day_write_offs enable row level security;

create policy day_write_offs_owner on day_write_offs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ─────────── 010_revision.sql ───────────
-- ============================================================================
-- 010_revision.sql
--
-- Spaced revision.
--
-- The solver schedules WORK. Revision is a different shape: the same topic
-- revisited at widening intervals, where the value is in the spacing, not the
-- hours. Forgetting is a curve, and a topic reviewed at day 2, 7 and 13 sticks
-- far better than the same minutes spent in one block.
--
-- Two triggers:
--   * a bad test — "I did badly in circular motion" — starts a cycle now
--   * a topic covered in class can start one on the same schedule
--
-- Each pass materialises as a real `tasks` row with a WINDOW (earliest_start
-- .. deadline) rather than a fixed date, so the existing solver places it
-- where there is genuinely room. No new scheduling machinery, and revision
-- automatically respects sleep, lessons, quotas and written-off days.
-- ============================================================================

do $guard$
begin
  if to_regclass('public.subjects') is null
     or to_regproc('public.set_updated_at') is null then
    raise exception
      'Migration 010 cannot run: migrations 001-009 are not present in this database. Check you are connected to the right Supabase project.';
  end if;
end
$guard$;

-- Re-runnable. Postgres has no `create type if not exists`, and re-running a
-- migration is a normal thing to do when you are unsure whether it took: the
-- bare form aborts the whole script on its first statement with "type
-- revision_origin already exists", which reads like damage when nothing has
-- happened at all.
do $revision_origin$
begin
  create type revision_origin as enum (
    'weak_spot',   -- flagged after a bad test or a lesson that did not land
    'syllabus',    -- routine coverage of a syllabus topic
    'manual'
  );
exception
  when duplicate_object then null;
end
$revision_origin$;

create table if not exists revision_topics (
  id           uuid primary key default gen_random_uuid(),
  user_id      uuid not null references auth.users (id) on delete cascade,
  subject_id   uuid references public.subjects (id) on delete cascade,

  label        text not null,
  origin       revision_origin not null default 'weak_spot',

  -- How shaky it feels, 1 = no idea .. 5 = solid. Drives how much time each
  -- pass gets, and whether the cycle restarts after a bad pass.
  confidence   smallint not null default 2 check (confidence between 1 and 5),

  -- The day the cycle was triggered. All pass offsets count from here.
  triggered_on date not null,
  is_active    boolean not null default true,

  notes        text,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists revision_topics_user_active_idx
  on revision_topics (user_id, subject_id) where is_active;

drop trigger if exists revision_topics_updated_at on revision_topics;
create trigger revision_topics_updated_at
  before update on revision_topics
  for each row execute function public.set_updated_at();

-- ---------------------------------------------------------------------------
-- One row per scheduled pass.
--
-- pass_index 0,1,2.. are the spaced passes; the final pre-exam pass is marked
-- separately because it is anchored to the exam session rather than to the
-- trigger date.
-- ---------------------------------------------------------------------------
create table if not exists revision_passes (
  id             uuid primary key default gen_random_uuid(),
  user_id        uuid not null references auth.users (id) on delete cascade,
  topic_id       uuid not null references revision_topics (id) on delete cascade,

  pass_index     smallint not null check (pass_index >= 0),
  is_pre_exam    boolean not null default false,

  -- The window the solver may place this pass in.
  earliest_on    date not null,
  due_on         date not null,

  estimate_min   int not null default 30 check (estimate_min > 0),
  -- Set once materialised, so generation stays idempotent.
  task_id        uuid references public.tasks (id) on delete set null,

  created_at     timestamptz not null default now(),

  constraint revision_window_ordered check (due_on >= earliest_on),
  -- A topic has exactly one pass per index: re-running generation cannot
  -- duplicate a cycle.
  unique (topic_id, pass_index)
);

create index if not exists revision_passes_due_idx on revision_passes (user_id, due_on);

alter table revision_topics  enable row level security;
alter table revision_passes  enable row level security;

drop policy if exists revision_topics_owner on revision_topics;
create policy revision_topics_owner on revision_topics
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists revision_passes_owner on revision_passes;
create policy revision_passes_owner on revision_passes
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- ─────────── 011_timetable_exceptions.sql ───────────
-- ============================================================================
-- 011_timetable_exceptions.sql
--
-- Cancelling ONE occurrence of a recurring commitment.
--
-- A timetable entry is a weekly pattern with a start and end date. That covers
-- "this lesson runs all term" and "this lesson stopped in December", but not
-- the ordinary case of a single week being off: a teaching session that does
-- not happen on the 27th, a cancelled club, a lesson lost to a school trip.
--
-- Without this the only options were both wrong. Delete the entry and you lose
-- every future week. Leave it and the solver keeps three hours blocked for
-- something that is not happening, so the plan quietly under-uses a day the
-- student actually had free.
--
-- An exception is a subtraction, never an edit: the pattern stays the single
-- source of truth and the exception records that one date is exempt from it.
-- Removing the exception restores the occurrence exactly, which is what makes
-- "I cancelled that by mistake" a one-click fix rather than a re-entry job.
-- ============================================================================

do $guard$
begin
  if to_regclass('public.timetable_entries') is null then
    raise exception
      'Migration 011 cannot run: migration 007 (timetable) is not present in this database. Either run supabase/FULL_SCHEMA.sql on a fresh project, or check you are connected to the right Supabase project.';
  end if;
end
$guard$;

create table if not exists timetable_exceptions (
  id         uuid primary key default gen_random_uuid(),
  user_id    uuid not null references auth.users (id) on delete cascade,
  entry_id   uuid not null references timetable_entries (id) on delete cascade,

  -- The local date this occurrence is skipped. Dates, not timestamps: "the
  -- 27th is off" is a calendar fact and must not shift with a timezone.
  on_date    date not null,

  -- Free text, shown back to the student so a cancellation made weeks ago is
  -- explicable rather than mysterious.
  reason     text,

  created_at timestamptz not null default now(),

  -- Cancelling twice is the same as cancelling once. This is what lets the
  -- command be re-run safely.
  unique (entry_id, on_date)
);

create index if not exists timetable_exceptions_lookup_idx
  on timetable_exceptions (user_id, on_date);

alter table timetable_exceptions enable row level security;

drop policy if exists timetable_exceptions_owner on timetable_exceptions;
create policy timetable_exceptions_owner on timetable_exceptions
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

comment on table timetable_exceptions is
  'One skipped occurrence of a recurring timetable entry. Subtractive: deleting the row restores the lesson.';

-- ─────────── 012_daily_focus_by_dow.sql ───────────
-- ============================================================================
-- 012_daily_focus_by_dow.sql
--
-- A per-weekday ceiling on focused study.
--
-- max_daily_focus_min is one number applied to all seven days, which models a
-- week nobody actually has. This student's Thursday is a school-sanctioned
-- self-study day with 685 free minutes; their Monday has seven hours of
-- lessons and 510. Both were rationed at 270, so Thursday discarded 415
-- minutes of capacity while the plan reported work it could not fit.
--
-- Stored as jsonb keyed by day of week ("0" = Sunday, matching
-- energy_profile.dow and timetable_entries.day_of_week) so adding a day costs
-- no migration. Null, or a missing key, falls back to max_daily_focus_min —
-- the flat number remains the default for anyone who has not set this.
-- ============================================================================

do $guard$
begin
  if to_regclass('public.user_settings') is null then
    raise exception
      'Migration 012 cannot run: migration 001 (foundation) is not present in this database.';
  end if;
end
$guard$;

alter table user_settings
  add column if not exists max_daily_focus_by_dow jsonb;

-- Postgres forbids a subquery inside CHECK, so the shape test lives in an
-- immutable function. Without it a typo becomes a day the solver believes has
-- forty hours in it.
create or replace function is_valid_focus_by_dow(v jsonb)
returns boolean
language sql
immutable
as $fn$
  select v is null or (
    jsonb_typeof(v) = 'object'
    and coalesce(
      (select bool_and(
                e.key in ('0','1','2','3','4','5','6')
                and jsonb_typeof(e.value) = 'number'
                and (e.value #>> '{}')::numeric between 0 and 960)
       from jsonb_each(v) as e),
      true)  -- an empty object is valid; it simply overrides nothing
  );
$fn$;

alter table user_settings drop constraint if exists focus_by_dow_shape;
alter table user_settings
  add constraint focus_by_dow_shape check (is_valid_focus_by_dow(max_daily_focus_by_dow));

comment on column user_settings.max_daily_focus_by_dow is
  'Per-weekday focus ceiling in minutes, keyed "0"-"6" with 0 = Sunday. Null or missing key falls back to max_daily_focus_min.';
