// AUTO-GENERATED by scripts/gen-types.mjs — do not edit by hand.
// Regenerate after any migration change: npm run db:types

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      ai_proposals: {
        Row: {
          id: string;
          user_id: string;
          kind: Database["public"]["Enums"]["proposal_kind"];
          status: Database["public"]["Enums"]["proposal_status"];
          payload: Json;
          model: string | null;
          confidence: number | null;
          source_kind: string;
          source_ref: string | null;
          is_trusted_source: boolean;
          validation_errors: Json | null;
          requires_confirmation: boolean;
          applied_run_id: string | null;
          applied_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          kind: Database["public"]["Enums"]["proposal_kind"];
          status?: Database["public"]["Enums"]["proposal_status"];
          payload: Json;
          model?: string | null;
          confidence?: number | null;
          source_kind?: string;
          source_ref?: string | null;
          is_trusted_source?: boolean;
          validation_errors?: Json | null;
          requires_confirmation?: boolean;
          applied_run_id?: string | null;
          applied_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          kind?: Database["public"]["Enums"]["proposal_kind"];
          status?: Database["public"]["Enums"]["proposal_status"];
          payload?: Json;
          model?: string | null;
          confidence?: number | null;
          source_kind?: string;
          source_ref?: string | null;
          is_trusted_source?: boolean;
          validation_errors?: Json | null;
          requires_confirmation?: boolean;
          applied_run_id?: string | null;
          applied_at?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "ai_proposals_applied_run_id_fkey";
            columns: ["applied_run_id"];
            isOneToOne: false;
            referencedRelation: "schedule_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "ai_proposals_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      assessments: {
        Row: {
          id: string;
          user_id: string;
          subject_id: string | null;
          kind: Database["public"]["Enums"]["assessment_kind"];
          title: string;
          due_at: string | null;
          grade_weight: number;
          is_external: boolean;
          status: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject_id?: string | null;
          kind: Database["public"]["Enums"]["assessment_kind"];
          title: string;
          due_at?: string | null;
          grade_weight?: number;
          is_external?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject_id?: string | null;
          kind?: Database["public"]["Enums"]["assessment_kind"];
          title?: string;
          due_at?: string | null;
          grade_weight?: number;
          is_external?: boolean;
          status?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "assessments_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "assessments_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      calendars: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          provider_calendar_id: string | null;
          color_token: string;
          is_visible: boolean;
          is_writable: boolean;
          is_app_managed: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          provider?: Database["public"]["Enums"]["calendar_provider"];
          provider_calendar_id?: string | null;
          color_token?: string;
          is_visible?: boolean;
          is_writable?: boolean;
          is_app_managed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          provider?: Database["public"]["Enums"]["calendar_provider"];
          provider_calendar_id?: string | null;
          color_token?: string;
          is_visible?: boolean;
          is_writable?: boolean;
          is_app_managed?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "calendars_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      energy_profile: {
        Row: {
          user_id: string;
          dow: number;
          hour: number;
          multiplier: number;
          samples: number;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          dow: number;
          hour: number;
          multiplier?: number;
          samples?: number;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          dow?: number;
          hour?: number;
          multiplier?: number;
          samples?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "energy_profile_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      estimation_calibration: {
        Row: {
          user_id: string;
          subject_id: string;
          cognitive_load: number;
          ratio_p50: number;
          ratio_p80: number;
          n_samples: number;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          subject_id: string;
          cognitive_load: number;
          ratio_p50?: number;
          ratio_p80?: number;
          n_samples?: number;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          subject_id?: string;
          cognitive_load?: number;
          ratio_p50?: number;
          ratio_p80?: number;
          n_samples?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "estimation_calibration_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "estimation_calibration_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      events: {
        Row: {
          id: string;
          user_id: string;
          calendar_id: string | null;
          subject_id: string | null;
          title: string;
          description: string | null;
          location: string | null;
          starts_at: string;
          ends_at: string;
          span: string | null;
          tier: number;
          kind: Database["public"]["Enums"]["event_kind"];
          is_locked: boolean;
          all_day: boolean;
          rrule: string | null;
          source: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          calendar_id?: string | null;
          subject_id?: string | null;
          title: string;
          description?: string | null;
          location?: string | null;
          starts_at: string;
          ends_at: string;
          tier?: number;
          kind?: Database["public"]["Enums"]["event_kind"];
          is_locked?: boolean;
          all_day?: boolean;
          rrule?: string | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          calendar_id?: string | null;
          subject_id?: string | null;
          title?: string;
          description?: string | null;
          location?: string | null;
          starts_at?: string;
          ends_at?: string;
          tier?: number;
          kind?: Database["public"]["Enums"]["event_kind"];
          is_locked?: boolean;
          all_day?: boolean;
          rrule?: string | null;
          source?: string;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "events_calendar_id_fkey";
            columns: ["calendar_id"];
            isOneToOne: false;
            referencedRelation: "calendars";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "events_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      integration_accounts: {
        Row: {
          id: string;
          user_id: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          provider_user_id: string | null;
          provider_email: string | null;
          access_token: string | null;
          refresh_token: string | null;
          token_expires_at: string | null;
          scopes: string[];
          needs_reauth: boolean;
          last_error: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          provider_user_id?: string | null;
          provider_email?: string | null;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expires_at?: string | null;
          scopes?: string[];
          needs_reauth?: boolean;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: Database["public"]["Enums"]["calendar_provider"];
          provider_user_id?: string | null;
          provider_email?: string | null;
          access_token?: string | null;
          refresh_token?: string | null;
          token_expires_at?: string | null;
          scopes?: string[];
          needs_reauth?: boolean;
          last_error?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "integration_accounts_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      momentum_snapshots: {
        Row: {
          user_id: string;
          day: string;
          planned_min: number;
          completed_min: number;
          rolling7_ratio: number;
          state: Database["public"]["Enums"]["momentum_state"];
          created_at: string;
        };
        Insert: {
          user_id: string;
          day: string;
          planned_min?: number;
          completed_min?: number;
          rolling7_ratio?: number;
          state?: Database["public"]["Enums"]["momentum_state"];
          created_at?: string;
        };
        Update: {
          user_id?: string;
          day?: string;
          planned_min?: number;
          completed_min?: number;
          rolling7_ratio?: number;
          state?: Database["public"]["Enums"]["momentum_state"];
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "momentum_snapshots_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      profiles: {
        Row: {
          id: string;
          display_name: string | null;
          timezone: string;
          ib_session: string | null;
          onboarded_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name?: string | null;
          timezone?: string;
          ib_session?: string | null;
          onboarded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string | null;
          timezone?: string;
          ib_session?: string | null;
          onboarded_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "profiles_id_fkey";
            columns: ["id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      retrospectives: {
        Row: {
          id: string;
          user_id: string;
          day: string;
          wins: Json;
          friction: Json;
          carryover: Json;
          energy_rating: number | null;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          day: string;
          wins?: Json;
          friction?: Json;
          carryover?: Json;
          energy_rating?: number | null;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          day?: string;
          wins?: Json;
          friction?: Json;
          carryover?: Json;
          energy_rating?: number | null;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "retrospectives_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      schedule_runs: {
        Row: {
          id: string;
          user_id: string;
          parent_run_id: string | null;
          horizon_start: string;
          horizon_end: string;
          input_hash: string;
          strategy: string;
          seed: number;
          status: string;
          is_active: boolean;
          infeasibility: Json;
          stats: Json;
          label: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          parent_run_id?: string | null;
          horizon_start: string;
          horizon_end: string;
          input_hash: string;
          strategy?: string;
          seed?: number;
          status?: string;
          is_active?: boolean;
          infeasibility?: Json;
          stats?: Json;
          label?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          parent_run_id?: string | null;
          horizon_start?: string;
          horizon_end?: string;
          input_hash?: string;
          strategy?: string;
          seed?: number;
          status?: string;
          is_active?: boolean;
          infeasibility?: Json;
          stats?: Json;
          label?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "schedule_runs_parent_run_id_fkey";
            columns: ["parent_run_id"];
            isOneToOne: false;
            referencedRelation: "schedule_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "schedule_runs_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      scheduled_blocks: {
        Row: {
          id: string;
          user_id: string;
          run_id: string;
          task_id: string;
          starts_at: string;
          ends_at: string;
          span: string | null;
          sequence_index: number;
          is_locked: boolean;
          energy_score: number | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          run_id: string;
          task_id: string;
          starts_at: string;
          ends_at: string;
          sequence_index?: number;
          is_locked?: boolean;
          energy_score?: number | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          run_id?: string;
          task_id?: string;
          starts_at?: string;
          ends_at?: string;
          sequence_index?: number;
          is_locked?: boolean;
          energy_score?: number | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "scheduled_blocks_run_id_fkey";
            columns: ["run_id"];
            isOneToOne: false;
            referencedRelation: "schedule_runs";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scheduled_blocks_task_id_fkey";
            columns: ["task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "scheduled_blocks_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      subjects: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          ib_group: number | null;
          level: Database["public"]["Enums"]["ib_level"];
          teacher: string | null;
          color_token: string;
          grade_weight: number;
          is_archived: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          ib_group?: number | null;
          level: Database["public"]["Enums"]["ib_level"];
          teacher?: string | null;
          color_token?: string;
          grade_weight?: number;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          ib_group?: number | null;
          level?: Database["public"]["Enums"]["ib_level"];
          teacher?: string | null;
          color_token?: string;
          grade_weight?: number;
          is_archived?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "subjects_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      sync_mappings: {
        Row: {
          id: string;
          user_id: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          local_table: string;
          local_id: string;
          remote_id: string;
          remote_etag: string | null;
          content_hash: string | null;
          last_synced_at: string;
          deleted_locally: boolean;
        };
        Insert: {
          id?: string;
          user_id: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          local_table: string;
          local_id: string;
          remote_id: string;
          remote_etag?: string | null;
          content_hash?: string | null;
          last_synced_at?: string;
          deleted_locally?: boolean;
        };
        Update: {
          id?: string;
          user_id?: string;
          provider?: Database["public"]["Enums"]["calendar_provider"];
          local_table?: string;
          local_id?: string;
          remote_id?: string;
          remote_etag?: string | null;
          content_hash?: string | null;
          last_synced_at?: string;
          deleted_locally?: boolean;
        };
        Relationships: [
          {
            foreignKeyName: "sync_mappings_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      sync_state: {
        Row: {
          user_id: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          sync_token: string | null;
          cursor: string | null;
          channel_id: string | null;
          channel_resource_id: string | null;
          channel_expires_at: string | null;
          last_full_sync_at: string | null;
          last_error: string | null;
          updated_at: string;
          sync_in_progress: boolean;
          consecutive_failures: number;
        };
        Insert: {
          user_id: string;
          provider: Database["public"]["Enums"]["calendar_provider"];
          sync_token?: string | null;
          cursor?: string | null;
          channel_id?: string | null;
          channel_resource_id?: string | null;
          channel_expires_at?: string | null;
          last_full_sync_at?: string | null;
          last_error?: string | null;
          updated_at?: string;
          sync_in_progress?: boolean;
          consecutive_failures?: number;
        };
        Update: {
          user_id?: string;
          provider?: Database["public"]["Enums"]["calendar_provider"];
          sync_token?: string | null;
          cursor?: string | null;
          channel_id?: string | null;
          channel_resource_id?: string | null;
          channel_expires_at?: string | null;
          last_full_sync_at?: string | null;
          last_error?: string | null;
          updated_at?: string;
          sync_in_progress?: boolean;
          consecutive_failures?: number;
        };
        Relationships: [
          {
            foreignKeyName: "sync_state_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      task_dependencies: {
        Row: {
          user_id: string;
          predecessor_id: string;
          successor_id: string;
          dep_type: Database["public"]["Enums"]["dependency_type"];
          lag_min: number;
          created_at: string;
        };
        Insert: {
          user_id: string;
          predecessor_id: string;
          successor_id: string;
          dep_type?: Database["public"]["Enums"]["dependency_type"];
          lag_min?: number;
          created_at?: string;
        };
        Update: {
          user_id?: string;
          predecessor_id?: string;
          successor_id?: string;
          dep_type?: Database["public"]["Enums"]["dependency_type"];
          lag_min?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "task_dependencies_predecessor_id_fkey";
            columns: ["predecessor_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_dependencies_successor_id_fkey";
            columns: ["successor_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "task_dependencies_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      tasks: {
        Row: {
          id: string;
          user_id: string;
          subject_id: string | null;
          assessment_id: string | null;
          parent_task_id: string | null;
          title: string;
          notes: string | null;
          estimate_min: number;
          remaining_min: number;
          actual_min: number;
          deadline_at: string | null;
          earliest_start_at: string | null;
          cognitive_load: number;
          splittable: boolean;
          min_chunk_min: number;
          max_chunk_min: number;
          status: Database["public"]["Enums"]["task_status"];
          priority_pin: number;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          subject_id?: string | null;
          assessment_id?: string | null;
          parent_task_id?: string | null;
          title: string;
          notes?: string | null;
          estimate_min?: number;
          remaining_min?: number;
          actual_min?: number;
          deadline_at?: string | null;
          earliest_start_at?: string | null;
          cognitive_load?: number;
          splittable?: boolean;
          min_chunk_min?: number;
          max_chunk_min?: number;
          status?: Database["public"]["Enums"]["task_status"];
          priority_pin?: number;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          subject_id?: string | null;
          assessment_id?: string | null;
          parent_task_id?: string | null;
          title?: string;
          notes?: string | null;
          estimate_min?: number;
          remaining_min?: number;
          actual_min?: number;
          deadline_at?: string | null;
          earliest_start_at?: string | null;
          cognitive_load?: number;
          splittable?: boolean;
          min_chunk_min?: number;
          max_chunk_min?: number;
          status?: Database["public"]["Enums"]["task_status"];
          priority_pin?: number;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "tasks_assessment_id_fkey";
            columns: ["assessment_id"];
            isOneToOne: false;
            referencedRelation: "assessments";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_parent_task_id_fkey";
            columns: ["parent_task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_subject_id_fkey";
            columns: ["subject_id"];
            isOneToOne: false;
            referencedRelation: "subjects";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "tasks_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      themes: {
        Row: {
          id: string;
          user_id: string;
          name: string;
          tokens: Json;
          source_image_url: string | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          name: string;
          tokens?: Json;
          source_image_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          name?: string;
          tokens?: Json;
          source_image_url?: string | null;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "themes_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      time_entries: {
        Row: {
          id: string;
          user_id: string;
          task_id: string | null;
          block_id: string | null;
          started_at: string;
          ended_at: string | null;
          duration_min: number | null;
          source: string;
          note: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          task_id?: string | null;
          block_id?: string | null;
          started_at: string;
          ended_at?: string | null;
          duration_min?: number | null;
          source?: string;
          note?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          task_id?: string | null;
          block_id?: string | null;
          started_at?: string;
          ended_at?: string | null;
          duration_min?: number | null;
          source?: string;
          note?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "time_entries_block_id_fkey";
            columns: ["block_id"];
            isOneToOne: false;
            referencedRelation: "scheduled_blocks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "time_entries_task_id_fkey";
            columns: ["task_id"];
            isOneToOne: false;
            referencedRelation: "tasks";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "time_entries_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: false;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
      user_settings: {
        Row: {
          user_id: string;
          sleep_start: string;
          sleep_end: string;
          sleep_protected: boolean;
          day_start: string;
          day_end: string;
          max_daily_focus_min: number;
          min_block_min: number;
          max_block_min: number;
          context_switch_penalty_min: number;
          planning_horizon_days: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          user_id: string;
          sleep_start?: string;
          sleep_end?: string;
          sleep_protected?: boolean;
          day_start?: string;
          day_end?: string;
          max_daily_focus_min?: number;
          min_block_min?: number;
          max_block_min?: number;
          context_switch_penalty_min?: number;
          planning_horizon_days?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          user_id?: string;
          sleep_start?: string;
          sleep_end?: string;
          sleep_protected?: boolean;
          day_start?: string;
          day_end?: string;
          max_daily_focus_min?: number;
          min_block_min?: number;
          max_block_min?: number;
          context_switch_penalty_min?: number;
          planning_horizon_days?: number;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_settings_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "users";
            referencedColumns: ["id"];
          },
        ];
      };
    };
    Views: { [_ in never]: never };
    Functions: {
      activate_schedule_run: {
        Args: {
          p_run_id: string;
        };
        Returns: undefined;
      };
    };
    Enums: {
      assessment_kind: "ia_draft" | "ia_final" | "ee_draft" | "ee_final" | "tok_essay" | "tok_exhibition" | "cas_reflection" | "mock" | "paper" | "oral" | "test" | "other";
      calendar_provider: "local" | "google" | "notion";
      dependency_type: "FS" | "SS" | "FF";
      event_kind: "class" | "exam" | "appointment" | "sleep" | "commitment" | "travel" | "general";
      ib_level: "HL" | "SL" | "CORE";
      momentum_state: "thriving" | "steady" | "strained" | "recovering";
      proposal_kind: "task_extract" | "estimate" | "classify" | "dependency" | "reschedule_intent" | "summarize";
      proposal_status: "pending" | "auto_approved" | "approved" | "rejected" | "applied" | "invalid";
      task_status: "todo" | "in_progress" | "blocked" | "done" | "dropped";
    };
    CompositeTypes: { [_ in never]: never };
  };
};
